### ISSUE TITLE
Problème lecture avec divx web player

### ISSUE THREAD

**Issue by wiinner69** [Cakebox/Cakebox-light#146]
Bonjour,
déjà merci pour cet utilitaire qui est génial.

J'ai un serveur kimsufi sur lequel j'ai installé cakebox light.
Le tout fonctionne très bien, excepté le lecteur divx.
Je peux parfaitement lire mes séries/films avec le lecteur HTML5, et vlc.
Par contre, impossible avec le lecteur divx ...

Quand je l'utilise et que je lance le film (je voudrais utiliser les divx pour les fichiers "MULTI" :p), j'ai très briévement un "chargement en cours" qui apparait, mais ça ne va pas plus loin.

J'ai installé Chrome en 32 bits, car j'ai vu que divx web player marchait avec cette version et pas forcément en 64 bits.

Je suis bien preneur d'une solution si quelqu'un a la moindre idée d'où vient le problème.
Merci :)

**Comment by ahyear** [comment]
bonjour,

le lecteur divix n'est pas hébergé sur le serveur mais sur l'ordinateur de l'utilisateur. ( celui qui va lire la video ).

Avez vous installé le divix player sur votre ordinateur?

**Comment by wiinner69** [comment]
Bonjour,
oui je l'ai bien installé (j'ai suivi le lien dans le wiki de cakebox light).
Puis j'ai installé le composant "divx web player" (je n'ai pas mis les autres car on en parlait pas dans le wiki). Mais dans une précédente installation, j'avais également divx player en plus du divx web player, et ça ne changeait pas mon problème. 

Merci en tout cas pour votre aide.

**Comment by ahyear** [comment]
c'est étrange parce que je viens de tester chez moi et ca fonctionne...
mais j'ai fait l'installation par defaut de divx player

**Comment by wiinner69** [comment]
Bah j'ai par sécurité installé le reste.
Sur la page : http://www.divx.com/fr/software/download/installed , j'arrive bien à lancer la vidéo.

Mais sur mon cakebox light, toujours pas.
ps : sur le site que j'ai donné, le temps de chargement a été assez long (chargement en cours est resté un moment, avec le logo divx qui était à moitié bleu). Je n'ai pas ce display là sur mon site de cakebox light :x

**Comment by martialdidit** [comment]
Si c'est long sur leur site alors que la vidéo fait que 14min, ça doit être encore plus long sur une vidéo de 40min.
Fait des tests avec une vidéo de quelques mo.

**Comment by wiinner69** [comment]
@martialdidit : je viens de tester sur un fichier de 6Go, sur un film MULTI, en http, et ça marche rapidement en fait.

Par contre, j'ai du faire un clic droit "executer ce plugin".
En https, j'ai direct le fond du divx web player, mais rien ne s'execute vraiment on dirait

**Comment by bxnxg** [comment]
DivX player ne marche pas chez moi quand le titre de la vidéo contient des.. crochets ex "Mavideo.h264.[Seedbox].mp4", si toutes tes vidéos ne se lancens pas, c'est peut être due à ton url http non ?

**Comment by Rajaskank** [comment]
Salut,

D'après DivX:

> Marcio, Technical Support Engineer
> The DivX Web Player is actually not currently supporting SSL / HTTPS.

Et c'est pareil pour tout les autres players, pour l'instant aucune solution pour l'HTTPS...

**Comment by Magicalex** [comment]
le player html5 peut lire en https (mais ne peut pas lire tous les formats..)

**Comment by Rajaskank** [comment]
Oui ça reste très limité...
