### ISSUE TITLE
Error 500 - Pas de problème de droit ...

### ISSUE THREAD

**Issue by desperadisse** [Cakebox/Cakebox-light#150]
Bonjour,
J'ai un soucis depuis la mise à jours de ma cakebox 1.8 à la 1.8.2
J'ai une erreur "Error 500 (Internal Server Error): GET api/directories" de ce type. 
J'ai vérifier tout les problème de droit, j'ai meme appliquer un crontab pour les droit et tous fonctionnait a merveille avant la MaJ.

Voici mon Cakebox error : 

2015/01/20 14:04:40 [error] 11975#0: *14 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "**************", referrer: "https://1********/cakebox/index.html"
2015/01/20 14:04:42 [error] 11975#0: *18 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "***", referrer: "https://**/cakebox/index.html"
2015/01/20 14:04:43 [error] 11975#0: *21 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "*********", referrer: "https://**********/cakebox/index.html"
2015/01/20 14:04:44 [error] 11975#0: *24 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "***************", referrer: "https://***********/cakebox/index.html"
2015/01/20 14:04:44 [error] 11975#0: *32 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "***************", referrer: "https://********/cakebox/index.html"
2015/01/20 14:04:46 [error] 11975#0: *41 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "**************", referrer: "https://***************/cakebox/index.html"
2015/01/20 14:04:46 [error] 11975#0: *44 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "***************", referrer: "https://************/cakebox/index.html"
2015/01/20 14:04:47 [error] 11975#0: *47 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "************", referrer: "https://***********/cakebox/index.html"
2015/01/20 14:04:47 [error] 11975#0: *50 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "**************", referrer: "https://***********/cakebox/index.html"
2015/01/20 14:04:47 [error] 11975#0: *53 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "****************", referrer: "https://**********/cakebox/index.html"
2015/01/20 14:04:47 [error] 11975#0: *56 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "*************", referrer: "https://************/cakebox/index.html"
2015/01/20 14:04:47 [error] 11975#0: *59 FastCGI sent in stderr: "PHP message: PHP Catchable fatal error:  Argument 1 passed to App\Models\Utils\get_size() must be an instance of Symfony\Component\Finder\SplFileInfo, instance of SplFileInfo given, called in /var/www/cakebox/app/controllers/directories.php on line 64 and defined in /var/www/cakebox/app/models/utils.php on line 15" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /api/directories?path= HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "**************", referrer: "https://***********/cakebox/index.html"

J'ai besoin de votre aide,
Merci d'avance

Bien Cordialement,
Despe

**Comment by martialdidit** [comment]
Bonjour,

Ligne 15 du fichier `app/models/utils.php`

Peut tu remplacer la ligne
```
function get_size(SplFileInfo $file) {
```

par :
```
function get_size(\SplFileInfo $file) {
```

Et tester le résultat ?

**Comment by desperadisse** [comment]
Je viens de le faire lol, et je viens surtout de voir ça ...

Merci c'est Ok pour moi ;)
Faudrai peut etre le mettre à jours directement non ? La MaJ m'a fait criser xD ^^

Merci encore

**Comment by martialdidit** [comment]
On ajoutera ça dans Cakebox 1.8.3 ^^ Certains on le problème, d'autres non, merci pour le report d'erreur :)
