### ISSUE TITLE
Mise à jour depuis ancienne version de cakebox ?

### ISSUE THREAD

**Issue by nfireseed** [Cakebox/Cakebox-light#151]
Bonjour, 

Je voulais juste savoir si le script de mise à jour est utilisable depuis l'ancienne version de cakebox (https://github.com/Cakebox/Cakebox) ?

Merci d'avance !

**Comment by martialdidit** [comment]
Non, mais tu peux tout à fait le faire manuellement !

**Comment by nfireseed** [comment]
Est-ce qu'il y a un tuto de la procédure à suivre ?

**Comment by martialdidit** [comment]
Pourquoi revenir à une ancienne version, généralement c'est jamais très bon de faire ça.

**Comment by nfireseed** [comment]
Non en fait c'est l'inverse, j'ai actuellement l'ancienne version et j'aimerai passer à Cakebox light.

**Comment by martialdidit** [comment]
Si le dossier contenant les videos n'est pas dans le dossier Cakebox, supprime le dossier cakebox et installe Cakebox-light avec le script :)

**Comment by nfireseed** [comment]
Merci !
