### ISSUE TITLE
Script apache

### ISSUE THREAD

**Issue by luniun** [Cakebox/Cakebox-light#157]
Bonjour, 

Le script apache " apache2-subdomain.sh" Me génère un fichier de conf, vide de paramètre.

Merci d'avance.

**Comment by mpgn** [comment]
Oui, la correction est faite, il faudrait créer la v1.8.3 @Tuxity qui corrige le problème des scripts apache.
En attendant @luniun tu peux directement prendre ce script : 

https://raw.githubusercontent.com/Cakebox/Cakebox-light/master/scripts/apache/apache2-alias.sh

**Comment by luniun** [comment]
Merci. Mais sa ne fonctionnent pas...

Le fichier est correctement cree, mais je tombe sur une page blanche..

**Comment by luniun** [comment]
En faite si je suprime 

RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [L]

Je tombe sur le site avec une erreur get api directory.  

Le probleme viendrais du rewrite? a2enmod rewrite (already activated)

**Comment by mpgn** [comment]
j'avais posté le script pour les alias, j'ai édit avec le bon lien :)

**Comment by luniun** [comment]
Page blanche Generer....

**Comment by mpgn** [comment]
post un petit pastbin de ton fichier de conf pour le subdomain stp

**Comment by luniun** [comment]
http://pastebin.com/m3TXT3YK

**Comment by mpgn** [comment]
tu veux un alias ou un sous domain ? la je comprend pas ce que tu veux vraiment

**Comment by luniun** [comment]
A la base ni l'un ni lautre. je le voudrais en site principal.

Mais je vien de test en sous domaine ,est jai toujours cette page blanche.

http://pastebin.com/LeEYdayM

**Comment by luniun** [comment]
Veux tu l'acce ssh pour verifier?

**Comment by ahyear** [comment]
essaye avec ca pour site principal ( version apache 2.4 ) ... en remplacant les DOMAIN.TLD pour ton site et les repertoirs par les tiens:

\<VirtualHost *:80>
ServerName DOMAIN.TLD
ServerAlias www.DOMAIN.TLD
DocumentRoot /home/to/cakebox/public
DirectoryIndex index.html index.htm index.php index.php4 index.php5
    \<Directory /home/to/cakebox/public/>
        Options Indexes MultiViews FollowSymLinks
        AllowOverride All

            Require all granted

        # use debug instead of production to get more log
        SetEnv APPLICATION_ENV debug

        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [QSA,L]
    \</Directory>

        Alias /access /home/to/files/to/stream
    \<Directory /home/to/files/to/stream>
        Options -Indexes

        Require all granted
        Satisfy Any

        Header set Content-Disposition "attachment"
    \</Directory>


\</VirtualHost>

**Comment by luniun** [comment]
apache2: Syntax error on line 268 of /etc/apache2/apache2.conf: Syntax error on line 30 of /etc/apache2/sites-enabled/000-default: Expected </Directory> but saw </VirtualHost>
Action 'configtest' failed.

**Comment by luniun** [comment]
github a couper on code je crois

**Comment by luniun** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, [no address given] and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache/2.2.22 (Debian) Server at 84.246.226.251 Port 80

**Comment by ahyear** [comment]
ok toi t'es en apache 2.2 donc ca change un peu

**Comment by ahyear** [comment]
\<VirtualHost *:80>
ServerName DOMAIN.TLD
ServerAlias www.DOMAIN.TLDt.tk
DocumentRoot /home/to/cakebox/public
DirectoryIndex index.html index.htm index.php index.php4 index.php5
    <Directory /home/to/cakebox/public/>
        Options Indexes MultiViews FollowSymLinks
        AllowOverride All

            order allow,deny
            allow from all

        # use debug instead of production to get more log
        SetEnv APPLICATION_ENV debug

        RewriteEngine On
        RewriteBase /
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [QSA,L]
    </Directory>

        Alias /access /home/to/files/to/stream
    <Directory /home/to/files/to/stream>
        Options -Indexes

            order allow,deny
            allow from all
        Satisfy Any

        Header set Content-Disposition "attachment"
    </Directory>


\</VirtualHost>

**Comment by luniun** [comment]
Expected </VirtualHost> but saw </Directory>

**Comment by ahyear** [comment]
la aussi il manque des bouts non?

**Comment by luniun** [comment]
http://pastebin.com/mwjwAweT

**Comment by ahyear** [comment]
http://pastebin.com/2qaSKA03

**Comment by luniun** [comment]
On revient a la page blanche.
http://84.246.226.251

**Comment by ahyear** [comment]
ben oui parce que la c'est pour le nom de domaine pas pour l'ip
http://DOMAIN.TLD

**Comment by luniun** [comment]
http://pastebin.com/JYK5MSCF

**Comment by ahyear** [comment]
d'ailleur ya une faute de frappe ligne 3 ( il faut aussi retirer le t.tk de la fin ^^ )

**Comment by luniun** [comment]
Sa ne fonctionera pas comme jai fais avec l'ip? http://pastebin.com/JYK5MSCF

Car mon nom de domaine est deja utiliser pour un autre site

**Comment by ahyear** [comment]
alors c'est encore autre chose...
il faut modifier le 000-default.conf ( apres l'avoir sauvegardé bien sur )

**Comment by luniun** [comment]
je suis sur le default la

**Comment by ahyear** [comment]
sinon essaye le premier fichier ( celui généré automatiquement ) en retirant les balises virtualhost et /virtualhost ( ca a marché pour d'autres )

**Comment by luniun** [comment]
Aucun changement

**Comment by luniun** [comment]
Veux tu la co SSH pour y voir plus clair?

**Comment by ahyear** [comment]
non ces données son perso et ne doivent pas circuler sur le net ;)
bon je dois partir de toutes façons mais passes sur le chat irc demain et on regardera ca.

**Comment by luniun** [comment]
Ok , merci a vous pour le temp passer
