### ISSUE TITLE
Index of /cakebox "again"

### ISSUE THREAD

**Issue by BlacKlWolf** [Cakebox/Cakebox-light#158]
Bonsoir,

J'ai configurer mon apache 2.2 avec un ALIAS utilisant un VPS sans nom de domaine.
Malheureusement quand je vais sur l'alias je tombe sur l'index après avoir essayé les conseils d'un sujet précédent du même nom je ne peux pas accéder à:
- /var/log/apache2/'$ALIAS' -error.log
- /var/log/apache2/'$ALIAS' -access.log

No Such file or directory pour les deux.

Je suis sous Debian 7, j'utilise deluge en tant que seedbox.
Quelqu'un pourrait m'aider ?

**Comment by mpgn** [comment]
Salut,

Supprime l'ancien fichier de conf et utilise ce script : 
https://github.com/Cakebox/Cakebox-light/blob/master/scripts/apache/apache2-alias.sh

l'autre n'est pas à jour.

**Comment by BlacKlWolf** [comment]
Merci pour la réponse.
Mais je ne parviens pas a executer ce script...
./apache2-alias.sh: 5: ./apache2-alias.sh: Syntax error: newline unexpected

C'est surement a cause de moi j'ai du faire un truc qui fallait pas, mais je ne vois pas.

**Comment by mpgn** [comment]
https://raw.githubusercontent.com/Cakebox/Cakebox-light/master/scripts/apache/apache2-alias.sh

**Comment by BlacKlWolf** [comment]
Merci, J'ai réessayer cette fois ci en changeant le nom de l'alias et la j'ai un joli 404.

**Comment by mpgn** [comment]
mon dans un pastbin le fichier de conf de l'alias

**Comment by BlacKlWolf** [comment]
<VirtualHost *:80>
    Alias /moonlight /var/www/cakebox/public/
    <Directory /var/www/cakebox/public/>
        Options Indexes MultiViews FollowSymLinks
        AllowOverride All

        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>

        # use debug instead of production to get more log
        SetEnv APPLICATION_ENV production

        RewriteEngine On
        RewriteBase /moonlight/
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^ index.php [QSA,L]
    </Directory>

    # alias for download and streaming, it must point to your download directory
    # replace /home/wolf with the same path as cakebox.root variable in app/config/
    Alias /access /home/wolf
    <Directory "/home/wolf">
        Options -Indexes

        <IfVersion >= 2.4>
            Require all granted
        </IfVersion>
        <IfVersion < 2.4>
            Order allow,deny
            Allow from all
        </IfVersion>
        Satisfy Any

        Header set Content-Disposition "attachment"
    </Directory>

    ErrorLog "/var/log/apache2/moonlight-error.log"
    CustomLog "/var/log/apache2/moonlight-access.log" common
</VirtualHost>

**Comment by mpgn** [comment]
rien dans les logs ?

```
/var/log/apache2/moonlight-error.log
/var/log/apache2/moonlight-access.log
```

**Comment by BlacKlWolf** [comment]
Non rien le vide absolue :/

**Comment by mpgn** [comment]
tu vois bien le fichier dans apache2/sites-enabled/ ?
Tu peux toujours essayé de viré les deux balises : 

`<VirtualHost *:80>` et `</VirtualHost>`
et redémarre apache
```
service apache2 restart
```
Si ca change rien, remet les.

**Comment by BlacKlWolf** [comment]
Oui les deux y sont je vais essayer d'enlever les virtualhost, je te tiens au courant.

**Comment by mpgn** [comment]
tu plus qu'a suivre les étapes de l'installe manuel :
https://github.com/Cakebox/Cakebox-light/wiki/Installation-de-Cakebox-light#installation-manuelle-

en sautant le git clone

**Comment by BlacKlWolf** [comment]
donc en fait c'est comme si j'avais rien fais x)

**Comment by mpgn** [comment]
ben le script apache n'a rien à voir avec l'installation proprement dite de cakebox

**Comment by BlacKlWolf** [comment]
oui ça ok mais en gros faut que je réinstalle tout du coup ? car j'ai refait l'installation manuel et rien ne change :/
et petit question pour composer c'est normal que je doivent taper composer.phar pour l’exécuter sinon il reconnais pas la commande ?

**Comment by BlacKlWolf** [comment]
Où est le dossier components ?
![1p2lq](https://cloud.githubusercontent.com/assets/10999361/6432962/7b2f8642-c063-11e4-8cb8-10133bedadee.jpg)

**Comment by mpgn** [comment]
tape la commande   `tree` dans le dossier cakebox qu'on voit ce qui manque

**Comment by BlacKlWolf** [comment]
Bon alors pour tout ceux qui ont été comme moi c'est EXTRÊMEMENT SIMPLE... aller dans votre dossier d'install cakebox et faite juste un SUDO bower install (--allow-root pour les utilisateur root évidement)

**Comment by mpgn** [comment]
@BlacKlWolf  ok !  bon stream alors :)

**Comment by BlacKlWolf** [comment]
Merci :D
