### ISSUE TITLE
Erreur script "install-cakebox" et Composer

### ISSUE THREAD

**Issue by Rajaskank** [Cakebox/Cakebox-light#159]
Salut,

Lors de l'installation de Cakebox (j'ai installé les pré-requis "à la main") il y avais une erreur avec composer.

Ligne 85:
> composer install

J'ai du le remplacer par:

> composer.phar install

Idem pour l'update ligne 113 et 114.

Après, aucun souci :wink:

Je tourne sous Debian Sid avec les dernières màj.

**Comment by mpgn** [comment]
je prend note pour une correction, merci !

**Comment by Rajaskank** [comment]
Avec plaisir :-)

**Comment by mpgn** [comment]
Done
