### ISSUE TITLE
Comment trier par défaut ?

### ISSUE THREAD

**Issue by lokiiiii** [Cakebox/cakebox-light#160]
Bonjour,

Y aurait-il un moyen de forcer une sorte de trie des fichiers par défaut?

Lorsque je vais sur ma cakebox depuis mon iphone, la vue est niquel: les dossiers en premiers par ordre alphabétique, suivis des fichiers en vrac, mais triés aussi par ordre alphabétique.
Par contre, sous mon mac, peut importe le navigateur, les fichiers et dossiers sont tous en vracs sans aucune cohérence. 
Est-il possible de forcer un listing par défaut de type " ls --group-directories-first" ?

Merci beaucoup, et encore bravo, j'ADORE cakebox :D

**Comment by Tuxity** [comment]
Hmmmm en effet je crois pas qu'il y ai possibilteée de faire ca facilement, en changeant un peu de code surement. On y pensera pour la V2
