### ISSUE TITLE
Update gulp files

### ISSUE THREAD

**Issue by Tuxity** [Cakebox/Cakebox-light#161]
Update gulp files to print warning in js files and things better. https://github.com/Swiip/generator-gulp-angular

**Comment by mpgn** [comment]
tu peux expliquer un peu, j'ai pas tous compris en lisant le code ?

**Comment by Tuxity** [comment]
Gulp c'est la meme chose que grunt. Sauf que Gulp devient de + en + populaire. La je voulais update les fichiers dans le dossier gulp car https://github.com/Swiip/generator-gulp-angular avait refactoré un peu beaucoup, et maintenant c'est un peu + fonctionnel et pratique.
