### ISSUE TITLE
Possibilité de tester cakebox light v2 ?

### ISSUE THREAD

**Issue by lokiiiii** [Cakebox/Cakebox-light#162]
Hello,
Est-il possible d'installer la v2 par dessus la 1.8.2 pour tester et faire des retours?
Merci.

**Comment by Magicalex** [comment]
Non pas pour l'instant elle est en développement.

**Comment by Tuxity** [comment]
Comme Magicalex l'a dit, celle ci est encore en développement. On fera une annonce quand elle sera prete a etre testée en version beta.
