### ISSUE TITLE
Error 404 (Not Found): GET api/directories 

### ISSUE THREAD

**Issue by furest** [Cakebox/cakebox-light#164]
Bonjour,
J'ai actuellement ce fameux problème d'erreur 404 quand je me connecte à cakebox (via xx.xx.xx.xx/cakebox)...
J'ai suivi le script de full installation auto fourni sur le github et suivi les tutos du wiki  sur la création de l'alias.
Malheureusement j'ai toujours le même problème et je n'arrive pas à le résoudre.

J'ai exécuté tout en tant que root.
Le dossier de scan (je suppose celui où se trouvent mes films) est /opt/rtorrent/download/
Le dossier dans lequel se trouve cakebox est /var/www/cakebox
Je n'ai pas vu de message d'erreur flagrant...

log apache : http://cjoint.com/?EDBtuQNjxHa

Furest

EDIT:
J'ai écrit Alias /cakebox /var/www/cakebox/public dans le apache.conf. J'ai réussi à me connecter au serveur avec XX.XX.XX.XX/cakebox et avoit l'interface mais le dossier API est toujours manquant...

**Comment by CLusmi** [comment]
chmod 777 /opt/rtorrent/download/

**Comment by ahyear** [comment]
a mon avis 777 c'est bien trop...
chmod -R 755 /opt/rtorrent/
ca suffit

**Comment by CLusmi** [comment]
Pour voir si l'erreur viens de là, un 777, et apres, a lui de voir ;)

**Comment by CLusmi** [comment]
Je rajouterais meme qu'en 755 je ne peux pas créer d'archive via cakebox.
Meme en 775; je suis obligé d'etre en 777 :/

**Comment by furest** [comment]
Re.
Je viens de tester chmod -r 777 /opt/rtorrent mais cela n'a rien changé...
selon moi c'est le script qui bug car dans la console JavaScript il est mentionné un dossier api (inexistant) à côté du dossier public. Et effectivement ce dossier est introuvable...

une idée de quoi faire peut-etre? ;)

**Comment by CLusmi** [comment]
chmod -R 777 /opt/rtorrent

Il faut le "R" en MAJUSCULE pour que ce chmod fonctionne ;)

Mais je pense que le probleme ne viens pas de la, et je ne suis pas assé competent pour voir plus loin, dsl ! Je te laisse les grands pros ;)

Sinon, il est toujours possible pour toi de voir les problemes similaires dans les Issues deja postées ! 

https://github.com/Cakebox/cakebox-light/issues?q=is%3Aissue+is%3Aclosed

Bon courage !

**Comment by furest** [comment]
J'ai bien effectué la commande comme dit (avec le R majuscule)... Mais rien ne change
Je pense que c'est un package manquant lors de l'installation mais je ne sais pas lequel... 
Il faudrait que quelqu'un sache ce qui est censé se trouver dans le fameux dossier api... ;)

**Comment by ahyear** [comment]
il y a bien le background avec les cupcakes?

**Comment by ahyear** [comment]
je pense qu'il faut faire cela en ligne de commandes:
a2dissite 000-default.conf
service apache2 restart

**Comment by Magicalex** [comment]
Il faut éviter d'une manière générale de mettre des chmod à 777
Il faut plutôt indiquer le bon propriétaire php pour le fichier. cf www-data

J'avais fait un tuto plutôt complet sur les droits qu'il faut mettre pour avoir accès à toutes les fonctionnalité de cakebox, plus la gestion du multi utilisateur.
Je joue avec les groupes et des réglages fin des droits sur les fichiers.
http://mondedie.fr/viewtopic.php?id=5314

D'ailleurs je peux le rajouter au wiki si @Tuxity trouve ça intéressant.

**Comment by furest** [comment]
Bon...
Petit point sur où j'en suis: 
chmod 777 fait sous toutes ses formes proposées
Tuto de Magicalex suivi pour les permissions des fichiers/dossiers.

J'ai du entre-temps réinstaller ma machine pour faire fonctionner le vps et ai installé rutorrent grâce au script rutorrent d'un certain kerwood.

J'ai réinstallé cakebox en suivant à la lettre l'installation manuelle des prérequis et de cakebox-light.

J'ai exécuté le script /var/www/cakebox/scripts/apache/apache2-alias.sh et lui ai renseigné mot pour mot les chemins demandés.

Résultat non probant puisque j'en suis revenu à me connecter via le dossier public et  que j'ai toujours l'erreur 404 me mentionnant l'inexistance du dossier API dans le dossier cakebox (personne n'en a encore parlé mais je le mentionne depuis le début... du coup j'ai pas trop compris si c'était normal qu'il ne soit pas là... :/)

Sinon, au lieu de taper des hordes de lignes de commandes inutiles, personne n'aurait autre chose d'aussi efficace que cakebox mais qui s'installe sans pépins? Parce que déjà que je suis une quiche lorraine pas cuite en linux mais en plus mes examens approchent donc j'ai encore moins de temps pour trifouiller...

Furest

**Comment by furest** [comment]
OOOOOH!
AAAAAAH!
ÉÉÉÉÉÉH!
CA MAAARCHE!

=> Je me suis référé à l'issue #158 et j'ai supprimé les balises <virtualhost * 80> et <virtualhost> et ça a fonctionné. On dirait bien que le script a besoin d'un petit fix ;)

Bref. Merci pour votre aide quand même :)

**Comment by CLusmi** [comment]
Rahhh, j'ai voulu te le dire, mais j'étais sur l'autoroute soleil dans la tronche :)
Bravo a toi et bon stream ;)

**Comment by furest** [comment]
Du coup c'est cool mais j'ai ouï dire qu'on pouvait choisir le lecteur que l'on voulait parmis vlc, divx et html5... quelqu'un a-t-il la moindre idée de comment je fais pour les avoir sur chrome sachant que j'ai déjà vlc d'installé sur le pc mais que chrome n'a pas l'air de vouloir de celui de windows? (chrome x64)

**Comment by ahyear** [comment]
chrome://flags/#enable-npapi
tu clic sur activer puis tu quite chrome completement et le relance.

**Comment by furest** [comment]
Whaaa t'es trop un génie :D Merci!
BTW j'ai proposé deux modifs : celle du fichier alias (ça évitera les futurs plaignants) et le rajout de ?> qui avait été oublié dans la config de rutorrent-cakebox-link ;)
