### ISSUE TITLE
Le search

### ISSUE THREAD

**Issue by pierreristic** [Cakebox/cakebox-light#166]
Hello !

Pas moyen d'utiliser le champ search chez moi. C'est un souci reconnu ? Merci !

**Comment by mpgn** [comment]
hum... la feature ne va pas chercher dans les sous dossiers. Juste les fichier dans le même répertoire.

**Comment by Tuxity** [comment]
Je confirme, cette partie ne filtre que le repertoire courant. La mise en place d'une recherche recursive dans tous les dossiers et sous-dossiers est un peu plus compliqué a mettre en place, peut etre plus tard.
